### ISSUE TITLE
Not able to use it

### ISSUE THREAD

**Issue by Aditya671** [Gaarv/kadenze-dl#14]
C:\kadenze-dl-master\kadenze-dl>python kadenze-dl.py
Traceback (most recent call last):
  File "kadenze-dl.py", line 1, in <module>
    from kadenzeclient import KadenzeClient
  File "C:\kadenze-dl-master\kadenze-dl\kadenzeclient.py", line 2, in <module>
    import helpers
  File "C:\kadenze-dl-master\kadenze-dl\helpers.py", line 5, in <module>
    from slugify import slugify
ModuleNotFoundError: No module named 'slugify'

please help...

**Comment by Gaarv** [comment]
Did you run `pip install -r requirements.txt` ?

**Comment by Aditya671** [comment]
Yes

**Comment by Gaarv** [comment]
I tried a fresh install on Windows and had no issues. Maybe you should try in a virtual environment to prevent any package conflict. I'm usually using conda with `conda create -n kadenze python=3.7 pip`
