### ISSUE TITLE
Can't run kadenze-dl (ERROR)

### ISSUE THREAD

**Issue by asapsmc** [Gaarv/kadenze-dl#15]
Hi!

I can't run kadenze-dl.py, as I get the following error:
```
Traceback (most recent call last):
  File "kadenze-dl.py", line 1, in <module>
    from kadenzeclient import KadenzeClient
  File "/Users/mactobe/Downloads/kadenze-dl-master/kadenze-dl/kadenzeclient.py", line 4, in <module>
    from robobrowser import RoboBrowser
  File "/Users/mactobe/anaconda3/envs/kadenze/lib/python3.6/site-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/Users/mactobe/anaconda3/envs/kadenze/lib/python3.6/site-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property'
```
Any idea what might be and how can I solve this??

**Comment by Gaarv** [comment]
Hi, sorry for the delay, it seems that I missed the issue notification :(
Thanks for reporting the issue, it seems that a transitive dependency (Werkzeug)broke a library I use.

I pinned the version in requirements.txt, so you just have to update by running `pip install -r requirements.txt`

**Comment by asapsmc** [comment]
Thank you!
