### ISSUE TITLE
Can't run python kadenze-dl.py

### ISSUE THREAD

**Issue by MartinezEzequiel1991** [Gaarv/kadenze-dl#17]
Sorry, I can't get through this error, I tried installing all de WHL files in the requirements.txt separately but I can't figure out what to do. I'm a basic user tried to figure things out. Thanks

I get this in the Windows PowerShell;
```
Traceback (most recent call last):
  File "kadenze-dl.py", line 10, in <module>
    main()
  File "kadenze-dl.py", line 5, in main
    client = KadenzeClient()
  File "C:\Users\Eze\Downloads\kadenze-dl-master\kadenze-dl\kadenzeclient.py", line 10, in __init__
    self.conf = Settings()
  File "C:\Users\Eze\Downloads\kadenze-dl-master\kadenze-dl\settings.py", line 7, in __init__
    self.config = yaml.load(configfile)
  File "C:\Python38\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "C:\Python38\lib\site-packages\yaml\constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Python38\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "C:\Python38\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Python38\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "C:\Python38\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Python38\lib\site-packages\yaml\scanner.py", line 248, in fetch_more_tokens
    return self.fetch_double()
  File "C:\Python38\lib\site-packages\yaml\scanner.py", line 652, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\Python38\lib\site-packages\yaml\scanner.py", line 663, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\Python38\lib\site-packages\yaml\scanner.py", line 1146, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "C:\Python38\lib\site-packages\yaml\scanner.py", line 1219, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "configuration.yml", line 6, column 11
found unknown escape character '#'
  in "configuration.yml", line 6, column 15
```

**Comment by MartinezEzequiel1991** [comment]
Config file was written bad, sorry
