### ISSUE TITLE
stops downloading and gives error if any video is locked for free users

### ISSUE THREAD

**Issue by fatimaj786** [Gaarv/kadenze-dl#21]
Can download half the course and then get this error...

(node:18940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 45)
(node:18940) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
at Socket._write (internal/net.js:54:25)
at doWrite (_stream_writable.js:403:12)
at writeOrBuffer (_stream_writable.js:387:5)
at Socket.Writable.write (_stream_writable.js:318:11)
at Transport.send (C:\Python39\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:47:25)
at DispatcherConnection.dispatcherConnection.onmessage (C:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:43:59)
at DispatcherConnection.sendMessageToClient (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:136:14)
at new Dispatcher (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:63:30)
at new JSHandleDispatcher (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\jsHandleDispatcher.js:25:9)
at Object.createHandle (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\elementHandlerDispatcher.js:22:90)
(node:18940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 46)
(node:18940) UnhandledPromiseRejectionWarning: Error: EPIPE: broken pipe, write
at Socket._write (internal/net.js:54:25)
at doWrite (_stream_writable.js:403:12)
at writeOrBuffer (_stream_writable.js:387:5)
at Socket.Writable.write (_stream_writable.js:318:11)
at Transport.send (C:\Python39\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:47:25)
at DispatcherConnection.dispatcherConnection.onmessage (C:\Python39\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:43:59)
at DispatcherConnection.sendMessageToClient (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:136:14)
at new Dispatcher (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\dispatcher.js:63:30)
at new JSHandleDispatcher (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\jsHandleDispatcher.js:25:9)
at Object.createHandle (C:\Python39\Lib\site-packages\playwright\driver\package\lib\dispatchers\elementHandlerDispatcher.js:22:90)
(node:18940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 47)

**Comment by Gaarv** [comment]
Yeah, still have to improve error catching.
Can you tell me in which course this occurs?

**Comment by fatimaj786** [comment]
Thanks a lot, Creative applications with tensorflow.

**Comment by Gaarv** [comment]
I've done some improvements in exceptions handling: if a video or session can't be accessed it would get to the next one and only displaying the error.

I only have free tier but no current access to one with locked items, so haven't tested in situation.
I will try to find one open for enrollment to improve how to handle this.

In the meantime, feel free to report any additional error on this.
