### ISSUE TITLE
downloading issue: KeyError: 'delete_lecture_path'

### ISSUE THREAD

**Issue by kfxs** [Gaarv/kadenze-dl#7]
$: python3 kadenze-dl.py 
Signing in www.kadenze.com ...
Parsing course: programming-max-structuring-interactive-software-for-digital-arts-i
Traceback (most recent call last):
  File "kadenze-dl.py", line 10, in <module>
    main()
  File "kadenze-dl.py", line 6, in main
    client.download_all_courses_videos()
  File "/home/user/kadenze-dl-master/kadenze-dl/kadenzeclient.py", line 69, in download_all_courses_videos
    self.download_course_videos(course)
  File "/home/user/kadenze-dl-master/kadenze-dl/kadenzeclient.py", line 55, in download_course_videos
    sessions = self.list_sessions(course)
  File "/home/user/kadenze-dl-master/kadenze-dl/kadenzeclient.py", line 34, in list_sessions
    sessions = helpers.get_sessions_from_json(response)
  File "/home/user/kadenze-dl-master/kadenze-dl/helpers.py", line 33, in get_sessions_from_json
    sessions = [session["delete_lecture_path"] for session in json_string["lectures"]]
  File "/home/user/kadenze-dl-master/kadenze-dl/helpers.py", line 33, in <listcomp>
    sessions = [session["delete_lecture_path"] for session in json_string["lectures"]]
KeyError: 'delete_lecture_path'

**Comment by Gaarv** [comment]
Hi, this issue was fixed with https://github.com/Gaarv/kadenze-dl/pull/6 , you will need to update your local copy with git pull

**Comment by kfxs** [comment]
Yes, it is fixed!
